name: liteline_app
description: A LINE clone application built with Flutter
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Storage
  shared_preferences: ^2.2.2
  
  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Camera & Media
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  video_player: ^2.7.2
  file_picker: ^6.1.1
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  geolocator: ^10.1.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # SMS Auto-fill
  sms_autofill: ^2.3.0
  
  # Utils
  intl: ^0.18.1
  uuid: ^4.1.0
  path_provider: ^2.1.1
  
  # Animations
  animations: ^2.0.8
  lottie: ^2.7.0
  
#video
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo/
    - assets/images/backgrounds/
    - assets/database/
  
  fonts:
    - family: LineFont
      fonts:
        - asset: assets/fonts/line_fonts/regular.ttf
        - asset: assets/fonts/line_fonts/bold.ttf
          weight: 700